#include "htmlreportgenerator.h"

#include "chartimagebuilder.h"

#include <QDateTime>
#include <QTextStream>

HtmlReportGenerator::HtmlReportGenerator(AnalyticsService *analyticsService)
    : AnalyticsReportGenerator(analyticsService)
{
}

ExportFormat HtmlReportGenerator::format() const
{
    return ExportFormat::Html;
}

GeneratedReport HtmlReportGenerator::generate(const ExportRequest& request)
{
    const ReportData data = loadReportData(request, 5);
    const QString generatedAt =
        QDateTime::currentDateTime().toString(QStringLiteral("yyyy-MM-dd HH:mm:ss"));

    QString html;
    QTextStream stream(&html);

    stream << "<!DOCTYPE html>\n";
    stream << "<html lang=\"en\">\n";
    stream << "<head>\n";
    stream << "  <meta charset=\"UTF-8\">\n";
    stream << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
    stream << "  <title>Social Media Analytics Report</title>\n";
    stream << "  <style>\n";
    stream << buildStyleSheet();
    stream << "  </style>\n";
    stream << "</head>\n";
    stream << "<body>\n";
    stream << "  <main class=\"page\">\n";
    stream << buildHeaderSection(request, generatedAt);
    stream << buildSummarySection(data.summary);
    stream << buildChartsSection(data);
    stream << buildPlatformTableSection(data.platformStats);
    stream << buildTopPostsTableSection(data.topPosts);
    stream << "    <footer class=\"footer\">Generated by Social Media Analytics Dashboard</footer>\n";
    stream << "  </main>\n";
    stream << "</body>\n";
    stream << "</html>\n";

    return makeHtmlReport(html);
}

/*
 * HTML 转义。
 *
 * 用户输入的账号名、正文内容可能包含 <、>、& 等字符，
 * 如果不转义，会破坏 HTML 结构。
 */
QString HtmlEscaper::htmlEscape(const QString& value) const
{
    QString escaped = value;

    escaped.replace(QStringLiteral("&"), QStringLiteral("&amp;"));
    escaped.replace(QStringLiteral("<"), QStringLiteral("&lt;"));
    escaped.replace(QStringLiteral(">"), QStringLiteral("&gt;"));
    escaped.replace(QStringLiteral("\""), QStringLiteral("&quot;"));
    escaped.replace(QStringLiteral("'"), QStringLiteral("&#39;"));

    return escaped;
}

/*
 * HTML 样式。
 *
 * - 浅灰背景；
 * - 白色卡片；
 * - 圆角边框；
 * - hero 报告头；
 * - metric-card 汇总卡片；
 * - chart-card 图表卡片；
 * - table-wrap 表格容器。
 */
QString HtmlReportGenerator::buildStyleSheet() const
{
    return QStringLiteral(R"(
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: #F5F7FB;
  color: #111827;
  font-family: "Microsoft YaHei", "PingFang SC", "Segoe UI", Arial, sans-serif;
  font-size: 14px;
}

.page {
  max-width: 1280px;
  margin: 0 auto;
  padding: 24px;
}

.hero {
  padding: 26px 28px;
  border-radius: 14px;
  background: #FFFFFF;
  border: 1px solid #E5E7EB;
}

.hero-badge {
  display: inline-block;
  margin-bottom: 12px;
  padding: 6px 12px;
  border-radius: 999px;
  background: #F3F4F6;
  color: #374151;
  font-size: 12px;
  font-weight: 700;
}

.hero h1 {
  margin: 0;
  color: #111827;
  font-size: 28px;
  line-height: 1.25;
  font-weight: 700;
}

.hero-desc {
  margin: 8px 0 20px;
  color: #6B7280;
  font-size: 13px;
}

.filter-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
  gap: 12px;
}

.filter-item {
  padding: 14px;
  border-radius: 12px;
  background: #F9FAFB;
  border: 1px solid #E5E7EB;
}

.filter-label {
  display: block;
  margin-bottom: 6px;
  color: #6B7280;
  font-size: 12px;
}

.filter-value {
  display: block;
  color: #111827;
  font-size: 14px;
  font-weight: 600;
}

.section {
  margin-top: 20px;
  padding: 18px;
  border-radius: 14px;
  background: #FFFFFF;
  border: 1px solid #E5E7EB;
}

.section-title {
  margin-bottom: 16px;
  color: #111827;
  font-size: 20px;
  font-weight: 700;
}

.metric-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 16px;
}

.metric-card {
  padding: 18px;
  border-radius: 12px;
  background: #FFFFFF;
  border: 1px solid #E5E7EB;
}

.metric-label {
  color: #6B7280;
  font-size: 13px;
}

.metric-value {
  margin-top: 10px;
  color: #111827;
  font-size: 30px;
  line-height: 1.1;
  font-weight: 700;
}

.metric-note {
  margin-top: 8px;
  color: #9CA3AF;
  font-size: 12px;
}

.chart-grid {
  display: grid;
  gap: 16px;
}

.chart-grid-two {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.chart-grid-one {
  margin-top: 16px;
  grid-template-columns: 1fr;
}

.chart-card {
  padding: 16px;
  border-radius: 12px;
  background: #FFFFFF;
  border: 1px solid #E5E7EB;
}

.chart-title {
  margin-bottom: 12px;
  color: #111827;
  font-size: 16px;
  font-weight: 700;
}

.chart-image-wrap {
  border-radius: 10px;
  background: #FFFFFF;
  overflow: hidden;
}

.chart-image {
  display: block;
  width: 100%;
  height: auto;
}

.table-wrap {
  overflow-x: auto;
  border: 1px solid #E5E7EB;
  border-radius: 10px;
}

table {
  width: 100%;
  border-collapse: collapse;
  background: #FFFFFF;
}

th,
td {
  padding: 12px 14px;
  text-align: left;
  border-bottom: 1px solid #E5E7EB;
  font-size: 13px;
  vertical-align: top;
}

th {
  background: #F9FAFB;
  color: #374151;
  font-weight: 600;
  white-space: nowrap;
}

tr:last-child td {
  border-bottom: none;
}

.empty-cell {
  color: #6B7280;
  font-size: 13px;
}

.footer {
  margin-top: 20px;
  text-align: center;
  color: #6B7280;
  font-size: 12px;
}

@media (max-width: 960px) {
  .chart-grid-two {
    grid-template-columns: 1fr;
  }
}

@media print {
  body {
    background: #FFFFFF;
  }

  .page {
    padding: 0;
  }
}
)");
}

QString HtmlReportGenerator::buildHeaderSection(const ExportRequest& request,
                                                const QString& generatedAt) const
{
    QString html;
    QTextStream stream(&html);

    stream << "    <header class=\"hero\">\n";
    stream << "      <div class=\"hero-badge\">HTML Visual Report</div>\n";
    stream << "      <h1>Social Media Analytics Report</h1>\n";
    stream << "      <p class=\"hero-desc\">This report exports both statistical data and visual charts.</p>\n";
    stream << "      <div class=\"filter-grid\">\n";

    auto filterItem = [&](const QString& label, const QString& value) {
        stream << "        <div class=\"filter-item\">\n";
        stream << "          <span class=\"filter-label\">" << htmlEscape(label) << "</span>\n";
        stream << "          <span class=\"filter-value\">" << htmlEscape(value) << "</span>\n";
        stream << "        </div>\n";
    };

    filterItem(QStringLiteral("Generated At"), generatedAt);
    filterItem(QStringLiteral("Date Range"), dateRangeText(request.filter));
    filterItem(QStringLiteral("Platform"), displayPlatform(request.filter.platform));
    filterItem(QStringLiteral("Data Scope"), scopeText(request.filter));

    stream << "      </div>\n";
    stream << "    </header>\n";

    return html;
}

QString HtmlReportGenerator::buildSummarySection(const DashboardSummary& summary) const
{
    QString html;
    QTextStream stream(&html);

    stream << "    <section class=\"section\">\n";
    stream << "      <div class=\"section-title\">Summary Statistics</div>\n";
    stream << "      <div class=\"metric-grid\">\n";

    auto metricCard = [&](const QString& label,
                          const QString& value,
                          const QString& note) {
        stream << "        <article class=\"metric-card\">\n";
        stream << "          <div class=\"metric-label\">" << htmlEscape(label) << "</div>\n";
        stream << "          <div class=\"metric-value\">" << htmlEscape(value) << "</div>\n";
        stream << "          <div class=\"metric-note\">" << htmlEscape(note) << "</div>\n";
        stream << "        </article>\n";
    };

    metricCard(QStringLiteral("Total Posts"),
               numberText(summary.totalPosts),
               QStringLiteral("Posts in current scope"));

    metricCard(QStringLiteral("Total Interactions"),
               numberText(summary.totalInteractions),
               QStringLiteral("Likes + comments + shares"));

    metricCard(QStringLiteral("Total Views"),
               numberText(summary.totalViews),
               QStringLiteral("Views in current scope"));

    metricCard(QStringLiteral("Engagement Rate"),
               percentText(summary.averageEngagementRate),
               QStringLiteral("Interactions / views"));

    stream << "      </div>\n";
    stream << "    </section>\n";

    return html;
}

QString HtmlReportGenerator::buildChartsSection(const ReportData& data) const
{
    const QString pieImage =
        ChartImageBuilder::pngDataUrl(
            ChartImageBuilder::buildPlatformPieChartPng(data.platformStats));

    const QString barImage =
        ChartImageBuilder::pngDataUrl(
            ChartImageBuilder::buildPlatformBarChartPng(data.platformStats));

    const QString trendImage =
        ChartImageBuilder::pngDataUrl(
            ChartImageBuilder::buildDailyTrendChartPng(data.dateTrends));

    QString html;
    QTextStream stream(&html);

    stream << "    <section class=\"section\">\n";
    stream << "      <div class=\"section-title\">Visual Charts</div>\n";

    stream << "      <div class=\"chart-grid chart-grid-two\">\n";

    stream << "        <article class=\"chart-card\">\n";
    stream << "          <div class=\"chart-title\">Platform Post Share</div>\n";
    stream << "          <div class=\"chart-image-wrap\">\n";
    stream << "            <img class=\"chart-image\" src=\"" << pieImage << "\" alt=\"Platform Post Share\">\n";
    stream << "          </div>\n";
    stream << "        </article>\n";

    stream << "        <article class=\"chart-card\">\n";
    stream << "          <div class=\"chart-title\">Platform Interactions</div>\n";
    stream << "          <div class=\"chart-image-wrap\">\n";
    stream << "            <img class=\"chart-image\" src=\"" << barImage << "\" alt=\"Platform Interactions\">\n";
    stream << "          </div>\n";
    stream << "        </article>\n";

    stream << "      </div>\n";

    stream << "      <div class=\"chart-grid chart-grid-one\">\n";
    stream << "        <article class=\"chart-card\">\n";
    stream << "          <div class=\"chart-title\">Interaction Trend</div>\n";
    stream << "          <div class=\"chart-image-wrap\">\n";
    stream << "            <img class=\"chart-image\" src=\"" << trendImage << "\" alt=\"Interaction Trend\">\n";
    stream << "          </div>\n";
    stream << "        </article>\n";
    stream << "      </div>\n";

    stream << "    </section>\n";

    return html;
}

QString HtmlReportGenerator::buildPlatformTableSection(
    const QList<PlatformStatistics>& platformStats) const
{
    QString html;
    QTextStream stream(&html);

    stream << "    <section class=\"section\">\n";
    stream << "      <div class=\"section-title\">Platform Statistics</div>\n";
    stream << "      <div class=\"table-wrap\">\n";
    stream << "        <table>\n";
    stream << "          <thead>\n";
    stream << "            <tr>\n";
    stream << "              <th>Platform</th>\n";
    stream << "              <th>Posts</th>\n";
    stream << "              <th>Likes</th>\n";
    stream << "              <th>Comments</th>\n";
    stream << "              <th>Shares</th>\n";
    stream << "              <th>Interactions</th>\n";
    stream << "              <th>Views</th>\n";
    stream << "              <th>Engagement</th>\n";
    stream << "            </tr>\n";
    stream << "          </thead>\n";
    stream << "          <tbody>\n";

    if (platformStats.isEmpty()) {
        stream << "            <tr><td class=\"empty-cell\" colspan=\"8\">No platform statistics available.</td></tr>\n";
    }

    for (const PlatformStatistics& stats : platformStats) {
        stream << "            <tr>\n";
        stream << "              <td>" << htmlEscape(stats.platform) << "</td>\n";
        stream << "              <td>" << numberText(stats.postCount) << "</td>\n";
        stream << "              <td>" << numberText(stats.totalLikes) << "</td>\n";
        stream << "              <td>" << numberText(stats.totalComments) << "</td>\n";
        stream << "              <td>" << numberText(stats.totalShares) << "</td>\n";
        stream << "              <td>" << numberText(stats.totalInteractions) << "</td>\n";
        stream << "              <td>" << numberText(stats.totalViews) << "</td>\n";
        stream << "              <td>" << htmlEscape(percentText(stats.averageEngagementRate)) << "</td>\n";
        stream << "            </tr>\n";
    }

    stream << "          </tbody>\n";
    stream << "        </table>\n";
    stream << "      </div>\n";
    stream << "    </section>\n";

    return html;
}

QString HtmlReportGenerator::buildTopPostsTableSection(const QList<Post>& topPosts) const
{
    QString html;
    QTextStream stream(&html);

    stream << "    <section class=\"section\">\n";
    stream << "      <div class=\"section-title\">Top Posts by Interactions</div>\n";
    stream << "      <div class=\"table-wrap\">\n";
    stream << "        <table>\n";
    stream << "          <thead>\n";
    stream << "            <tr>\n";
    stream << "              <th>Rank</th>\n";
    stream << "              <th>Platform</th>\n";
    stream << "              <th>Account</th>\n";
    stream << "              <th>Content</th>\n";
    stream << "              <th>Publish Date</th>\n";
    stream << "              <th>Interactions</th>\n";
    stream << "              <th>Views</th>\n";
    stream << "              <th>Engagement</th>\n";
    stream << "            </tr>\n";
    stream << "          </thead>\n";
    stream << "          <tbody>\n";

    if (topPosts.isEmpty()) {
        stream << "            <tr><td class=\"empty-cell\" colspan=\"8\">No post data available.</td></tr>\n";
    }

    int rank = 1;

    for (const Post& post : topPosts) {
        stream << "            <tr>\n";
        stream << "              <td>" << rank << "</td>\n";
        stream << "              <td>" << htmlEscape(post.platform) << "</td>\n";
        stream << "              <td>" << htmlEscape(post.accountName) << "</td>\n";
        stream << "              <td>" << htmlEscape(shortText(post.content, 120)) << "</td>\n";
        stream << "              <td>" << htmlEscape(post.publishDate.toString(QStringLiteral("yyyy-MM-dd"))) << "</td>\n";
        stream << "              <td>" << numberText(post.interactionCount()) << "</td>\n";
        stream << "              <td>" << numberText(post.views) << "</td>\n";
        stream << "              <td>" << htmlEscape(percentText(post.engagementRate())) << "</td>\n";
        stream << "            </tr>\n";

        ++rank;
    }

    stream << "          </tbody>\n";
    stream << "        </table>\n";
    stream << "      </div>\n";
    stream << "    </section>\n";

    return html;
}